using System;
using System.Collections.Generic;
using System.Linq;

public static class TimedLevelValidator
{
    public static void ValidateForGeneration(TimedLevelDefinition definition, BoardStateSnapshot board)
    {
        ValidateDefinition(definition);
        ValidateBoard(definition, board);
    }

    public static void ValidateForRuntime(TimedLevelDefinition definition, BoardStateSnapshot board, int generatorVersion)
    {
        ValidateForGeneration(definition, board);

        if (generatorVersion <= 0)
            throw new ArgumentOutOfRangeException(nameof(generatorVersion));

        if (definition.Variants == null || definition.Variants.Count == 0)
            throw new InvalidOperationException($"{definition.name}: no verified variants are configured.");

        HashSet<int> seeds = new HashSet<int>();

        for (int index = 0; index < definition.Variants.Count; index++)
        {
            TimedLevelVariant variant = definition.Variants[index];

            if (variant == null)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} is missing.");

            if (!seeds.Add(variant.Seed))
                throw new InvalidOperationException($"{definition.name}: seed {variant.Seed} is duplicated.");

            if (variant.GeneratorVersion != generatorVersion)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} was generated by version {variant.GeneratorVersion}, expected {generatorVersion}.");

            if (variant.MoveCount <= 0 || string.IsNullOrWhiteSpace(variant.LayoutHash))
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} is not verified.");

            if (!variant.HasLayout || BoardStateFingerprint.CreateHash(variant.CreateLayout()) != variant.LayoutHash)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} layout is missing or corrupted.");

            if (!variant.HasSolution)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} solution is missing.");

            ValidateVariantLayout(definition, board, variant, index);
        }
    }

    public static int GetItemCount(TimedLevelDefinition definition, int matchSize)
    {
        if (definition == null)
            throw new ArgumentNullException(nameof(definition));

        if (matchSize < ShelfStateSnapshot.MinimumMatchCapacity || matchSize > ShelfStateSnapshot.MaximumCapacity)
            throw new ArgumentOutOfRangeException(nameof(matchSize));

        return definition.ItemGroups.Sum(group => checked(group.GroupCount * matchSize));
    }

    private static void ValidateDefinition(TimedLevelDefinition definition)
    {
        if (definition == null)
            throw new ArgumentNullException(nameof(definition));

        if (definition.ThreeStarTimeSeconds <= 0
            || definition.ThreeStarTimeSeconds >= definition.TwoStarTimeSeconds
            || definition.TwoStarTimeSeconds >= definition.TimeLimitSeconds)
        {
            throw new InvalidOperationException($"{definition.name}: time thresholds must satisfy 0 < three stars < two stars < time limit.");
        }

        if (definition.EmptyColumnCount <= 0)
            throw new InvalidOperationException($"{definition.name}: at least one empty column is required.");

        if (definition.ItemCatalog == null)
            throw new InvalidOperationException($"{definition.name}: item catalog is missing.");

        definition.ItemCatalog.Validate();

        if (definition.ItemGroups == null || definition.ItemGroups.Count == 0)
            throw new InvalidOperationException($"{definition.name}: item groups are missing.");

        HashSet<ItemType> types = new HashSet<ItemType>();

        for (int index = 0; index < definition.ItemGroups.Count; index++)
        {
            TimedLevelItemGroup group = definition.ItemGroups[index];

            if (group == null)
                throw new InvalidOperationException($"{definition.name}: item group {index + 1} is missing.");

            if (group.GroupCount <= 0)
                throw new InvalidOperationException($"{definition.name}: {group.Type} must contain at least one group.");

            if (!types.Add(group.Type))
                throw new InvalidOperationException($"{definition.name}: {group.Type} is duplicated.");

            definition.ItemCatalog.GetPrefab(group.Type);
        }
    }

    private static void ValidateBoard(TimedLevelDefinition definition, BoardStateSnapshot board)
    {
        if (board == null)
            throw new ArgumentNullException(nameof(board));

        if (board.Shelves.Count == 0)
            throw new InvalidOperationException($"{definition.name}: the scene board has no shelves.");

        int matchSize = board.Shelves[0].Capacity;

        if (matchSize < ShelfStateSnapshot.MinimumMatchCapacity)
            throw new InvalidOperationException($"{definition.name}: shelf capacity {matchSize} cannot form a match.");

        if (board.Shelves.Any(shelf => shelf.Capacity != matchSize))
            throw new InvalidOperationException($"{definition.name}: all scene shelves must have the same capacity.");

        int columnCount = board.Shelves.Sum(shelf => shelf.Capacity);

        if (definition.EmptyColumnCount >= columnCount)
            throw new InvalidOperationException($"{definition.name}: empty column reserve leaves no space for items.");

        int itemCount = GetItemCount(definition, matchSize);

        if (itemCount <= 0)
            throw new InvalidOperationException($"{definition.name}: the level contains no items.");

        int usableColumnCount = columnCount - definition.EmptyColumnCount;
        int requiredDepth = (itemCount + usableColumnCount - 1) / usableColumnCount;

        if (requiredDepth > TimedLevelLayoutRules.MaximumColumnDepth)
            throw new InvalidOperationException($"{definition.name}: {itemCount} items exceed the supported column depth of {TimedLevelLayoutRules.MaximumColumnDepth}.");
    }

    private static void ValidateVariantLayout(TimedLevelDefinition definition, BoardStateSnapshot board, TimedLevelVariant variant, int variantIndex)
    {
        BoardStateSnapshot layout = variant.CreateLayout();

        if (layout.Shelves.Count != board.Shelves.Count)
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incompatible shelf count.");

        for (int shelfIndex = 0; shelfIndex < layout.Shelves.Count; shelfIndex++)
        {
            ShelfStateSnapshot shelf = layout.Shelves[shelfIndex];

            if (shelf.Capacity != board.Shelves[shelfIndex].Capacity)
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incompatible shelf capacity.");

            if (shelf.HasMatch())
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} starts with an automatic match.");

            if (shelf.Columns.Any(column => column.Count > TimedLevelLayoutRules.MaximumColumnDepth))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} exceeds the supported column depth.");

            if (shelf.Columns.Any(HasAdjacentDuplicate))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} contains adjacent items of the same type in a column.");
        }

        if (layout.EmptyColumnCount != definition.EmptyColumnCount)
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has {layout.EmptyColumnCount} empty columns instead of {definition.EmptyColumnCount}.");

        int matchSize = board.Shelves[0].Capacity;
        Dictionary<ItemType, int> expectedCounts = definition.ItemGroups.ToDictionary(
            group => group.Type,
            group => checked(group.GroupCount * matchSize));
        Dictionary<ItemType, int> actualCounts = layout.Shelves
            .SelectMany(shelf => shelf.Columns)
            .SelectMany(column => column.Items)
            .GroupBy(type => type)
            .ToDictionary(group => group.Key, group => group.Count());

        if (expectedCounts.Count != actualCounts.Count
            || expectedCounts.Any(pair => !actualCounts.TryGetValue(pair.Key, out int count) || count != pair.Value))
        {
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} item counts differ from the definition.");
        }
    }

    private static bool HasAdjacentDuplicate(ColumnStateSnapshot column)
    {
        for (int index = 1; index < column.Count; index++)
        {
            if (column.Items[index] == column.Items[index - 1])
                return true;
        }

        return false;
    }
}
