using System;
using System.Collections.Generic;
using System.Linq;

public static class TimedLevelValidator
{
    public static void ValidateForGeneration(TimedLevelDefinition definition, BoardStateSnapshot board)
    {
        ValidateDefinition(definition);
        ValidateBoard(definition, board);
    }

    public static void ValidateForRuntime(TimedLevelDefinition definition, BoardStateSnapshot board, int generatorVersion)
    {
        ValidateForGeneration(definition, board);

        if (generatorVersion <= 0)
            throw new ArgumentOutOfRangeException(nameof(generatorVersion));

        if (definition.Variants == null || definition.Variants.Count == 0)
            throw new InvalidOperationException($"{definition.name}: no verified variants are configured.");

        HashSet<int> seeds = new HashSet<int>();

        for (int index = 0; index < definition.Variants.Count; index++)
        {
            TimedLevelVariant variant = definition.Variants[index];

            if (variant == null)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} is missing.");

            if (!seeds.Add(variant.Seed))
                throw new InvalidOperationException($"{definition.name}: seed {variant.Seed} is duplicated.");

            if (variant.GeneratorVersion != generatorVersion)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} was generated by version {variant.GeneratorVersion}, expected {generatorVersion}.");

            if (variant.MoveCount <= 0 || string.IsNullOrWhiteSpace(variant.LayoutHash))
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} is not verified.");

            if (!variant.HasLayout || BoardStateFingerprint.CreateHash(variant.CreateLayout()) != variant.LayoutHash)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} layout is missing or corrupted.");

            if (!variant.HasSolution)
                throw new InvalidOperationException($"{definition.name}: variant {index + 1} solution is missing.");

            ValidateVariantLayout(definition, board, variant, index);
        }
    }

    public static int GetItemCount(TimedLevelDefinition definition, int matchSize)
    {
        if (definition == null)
            throw new ArgumentNullException(nameof(definition));

        if (matchSize < ShelfStateSnapshot.MinimumMatchCapacity || matchSize > ShelfStateSnapshot.MaximumCapacity)
            throw new ArgumentOutOfRangeException(nameof(matchSize));

        return definition.ItemGroups.Sum(group => checked(group.GroupCount * matchSize));
    }

    private static void ValidateDefinition(TimedLevelDefinition definition)
    {
        if (definition == null)
            throw new ArgumentNullException(nameof(definition));

        if (definition.ThreeStarTimeSeconds <= 0
            || definition.ThreeStarTimeSeconds >= definition.TwoStarTimeSeconds
            || definition.TwoStarTimeSeconds >= definition.TimeLimitSeconds)
        {
            throw new InvalidOperationException($"{definition.name}: time thresholds must satisfy 0 < three stars < two stars < time limit.");
        }

        if (definition.EmptyColumnCount <= 0)
            throw new InvalidOperationException($"{definition.name}: at least one empty column is required.");

        if (definition.ItemCatalog == null)
            throw new InvalidOperationException($"{definition.name}: item catalog is missing.");

        definition.ItemCatalog.Validate();

        if (definition.ItemGroups == null || definition.ItemGroups.Count == 0)
            throw new InvalidOperationException($"{definition.name}: item groups are missing.");

        HashSet<ItemType> types = new HashSet<ItemType>();

        for (int index = 0; index < definition.ItemGroups.Count; index++)
        {
            TimedLevelItemGroup group = definition.ItemGroups[index];

            if (group == null)
                throw new InvalidOperationException($"{definition.name}: item group {index + 1} is missing.");

            if (group.GroupCount <= 0)
                throw new InvalidOperationException($"{definition.name}: {group.Type} must contain at least one group.");

            if (!types.Add(group.Type))
                throw new InvalidOperationException($"{definition.name}: {group.Type} is duplicated.");

            definition.ItemCatalog.GetPrefab(group.Type);
        }

        if (definition.ConveyorShelfIndices.Any(index => index < 0))
            throw new InvalidOperationException($"{definition.name}: conveyor shelf indices must be non-negative.");

        if (definition.ConveyorShelfIndices.Distinct().Count() != definition.ConveyorShelfIndices.Count)
            throw new InvalidOperationException($"{definition.name}: a conveyor shelf index is duplicated.");

        if (definition.HasConveyors && definition.HasClosedShelves)
            throw new InvalidOperationException($"{definition.name}: conveyors and closed shelves cannot share a level.");

        if (definition.HasShelfFilters && definition.HasClosedShelves)
            throw new InvalidOperationException($"{definition.name}: shelf filters and closed shelves cannot share a level.");

        if (definition.HasConveyors && definition.ShuffleSwapCount > 0)
            throw new InvalidOperationException($"{definition.name}: shuffle swaps are not supported on conveyor levels.");

        if ((definition.RefillSettings != null) != definition.HasClosedShelves)
            throw new InvalidOperationException($"{definition.name}: refill settings must be configured exactly when closed shelves are present.");

        foreach (ClosedShelfDefinition closedShelf in definition.ClosedShelves)
        {
            if (closedShelf.RevealedGroupCount <= 0 || closedShelf.RevealedGroupCount % 3 != 0)
                throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} revealed group count must be a positive multiple of three.");

            switch (closedShelf.Condition)
            {
                case ShelfUnlockConditionKind.CollectItems:
                    if (closedShelf.RequiredItems.Count == 0 || closedShelf.RequiredItems.Count > 3)
                        throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} must require one to three item types.");

                    HashSet<ItemType> requiredTypes = new HashSet<ItemType>();

                    foreach (ItemRequirement requirement in closedShelf.RequiredItems)
                    {
                        if (!types.Contains(requirement.Type))
                            throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} requires {requirement.Type}, which is not one of the level's item types.");

                        if (requirement.Count <= 0 || requirement.Count % 3 != 0)
                            throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} requires a positive multiple of three of {requirement.Type}.");

                        if (!requiredTypes.Add(requirement.Type))
                            throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} requires {requirement.Type} twice.");
                    }
                    break;

                case ShelfUnlockConditionKind.MatchesOnShelf:
                    if (closedShelf.RequiredCount <= 0)
                        throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} requires a positive count.");
                    break;
            }
        }

        ValidateShelfFilterDefinition(definition, types);
    }

    private static void ValidateShelfFilterDefinition(TimedLevelDefinition definition, HashSet<ItemType> levelTypes)
    {
        if (!definition.HasShelfFilters)
        {
            if (definition.FilteredEmptyColumnCount != 0)
                throw new InvalidOperationException($"{definition.name}: filtered empty columns require shelf filters.");

            return;
        }

        if (definition.FilteredEmptyColumnCount > definition.EmptyColumnCount)
            throw new InvalidOperationException($"{definition.name}: filtered empty columns exceed the empty column reserve.");

        HashSet<int> filteredShelfIndices = new HashSet<int>();

        foreach (ShelfFilterDefinition shelfFilter in definition.ShelfFilters)
        {
            if (shelfFilter == null)
                throw new InvalidOperationException($"{definition.name}: a shelf filter is missing.");

            if (shelfFilter.ShelfIndex < 0)
                throw new InvalidOperationException($"{definition.name}: shelf filter indices must be non-negative.");

            if (!filteredShelfIndices.Add(shelfFilter.ShelfIndex))
                throw new InvalidOperationException($"{definition.name}: shelf {shelfFilter.ShelfIndex} is filtered twice.");

            IReadOnlyList<ItemType> acceptedTypes = shelfFilter.AcceptedTypes;

            if (acceptedTypes.Count == 0 || acceptedTypes.Count > TimedLevelLayoutRules.MaximumAcceptedTypeCount)
                throw new InvalidOperationException($"{definition.name}: shelf filter {shelfFilter.ShelfIndex} must accept one to {TimedLevelLayoutRules.MaximumAcceptedTypeCount} item types.");

            if (acceptedTypes.Distinct().Count() != acceptedTypes.Count)
                throw new InvalidOperationException($"{definition.name}: shelf filter {shelfFilter.ShelfIndex} accepts an item type twice.");

            foreach (ItemType type in acceptedTypes)
            {
                if (!levelTypes.Contains(type))
                    throw new InvalidOperationException($"{definition.name}: shelf filter {shelfFilter.ShelfIndex} accepts {type}, which is not one of the level's item types.");

                definition.ItemCatalog.GetSignIcon(type);
            }

            if (acceptedTypes.Count >= levelTypes.Count)
                throw new InvalidOperationException($"{definition.name}: shelf filter {shelfFilter.ShelfIndex} accepts every item type of the level.");
        }
    }

    private static void ValidateBoard(TimedLevelDefinition definition, BoardStateSnapshot board)
    {
        if (board == null)
            throw new ArgumentNullException(nameof(board));

        if (board.Shelves.Count == 0)
            throw new InvalidOperationException($"{definition.name}: the scene board has no shelves.");

        int matchSize = board.Shelves[0].Capacity;

        if (matchSize < ShelfStateSnapshot.MinimumMatchCapacity)
            throw new InvalidOperationException($"{definition.name}: shelf capacity {matchSize} cannot form a match.");

        if (board.Shelves.Any(shelf => shelf.Capacity != matchSize))
            throw new InvalidOperationException($"{definition.name}: all scene shelves must have the same capacity.");

        int columnCount = board.Shelves.Sum(shelf => shelf.Capacity);

        if (definition.EmptyColumnCount >= columnCount)
            throw new InvalidOperationException($"{definition.name}: empty column reserve leaves no space for items.");

        int closedColumnCount = 0;

        if (definition.HasClosedShelves)
        {
            if (definition.ClosedShelves.Count >= board.Shelves.Count)
                throw new InvalidOperationException($"{definition.name}: closed shelves cannot cover the whole board.");

            if (board.Shelves.Any(shelf => shelf.Capacity != 3))
                throw new InvalidOperationException($"{definition.name}: closed-shelf levels require shelf capacity 3.");

            HashSet<int> closedIndices = new HashSet<int>();

            foreach (ClosedShelfDefinition closedShelf in definition.ClosedShelves)
            {
                if (closedShelf.ShelfIndex < 0 || closedShelf.ShelfIndex >= board.Shelves.Count)
                    throw new InvalidOperationException($"{definition.name}: closed shelf index {closedShelf.ShelfIndex} is out of range.");

                if (!closedIndices.Add(closedShelf.ShelfIndex))
                    throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} is closed twice.");
            }

            foreach (ClosedShelfDefinition closedShelf in definition.ClosedShelves)
            {
                if (closedShelf.Condition != ShelfUnlockConditionKind.MatchesOnShelf)
                    continue;

                if (closedShelf.TargetShelfIndex < 0 || closedShelf.TargetShelfIndex >= board.Shelves.Count || closedIndices.Contains(closedShelf.TargetShelfIndex))
                    throw new InvalidOperationException($"{definition.name}: shelf {closedShelf.ShelfIndex} targets a missing or closed shelf.");
            }

            closedColumnCount = definition.ClosedShelves.Sum(closedShelf => board.Shelves[closedShelf.ShelfIndex].Capacity);
        }

        int itemCount = GetItemCount(definition, matchSize);

        if (itemCount <= 0)
            throw new InvalidOperationException($"{definition.name}: the level contains no items.");

        int usableColumnCount = columnCount - definition.EmptyColumnCount - closedColumnCount;

        if (usableColumnCount <= 0)
            throw new InvalidOperationException($"{definition.name}: closed and reserved columns leave no space for items.");

        int requiredDepth = (itemCount + usableColumnCount - 1) / usableColumnCount;

        if (requiredDepth > TimedLevelLayoutRules.MaximumColumnDepth)
            throw new InvalidOperationException($"{definition.name}: {itemCount} items exceed the supported column depth of {TimedLevelLayoutRules.MaximumColumnDepth}.");

        if (definition.HasConveyors)
            ValidateConveyorBoard(definition, board, columnCount, itemCount);

        if (definition.HasShelfFilters)
            ValidateShelfFilterBoard(definition, board);
    }

    private static void ValidateShelfFilterBoard(TimedLevelDefinition definition, BoardStateSnapshot board)
    {
        foreach (ShelfFilterDefinition shelfFilter in definition.ShelfFilters)
        {
            if (shelfFilter.ShelfIndex >= board.Shelves.Count)
                throw new InvalidOperationException($"{definition.name}: shelf filter index {shelfFilter.ShelfIndex} is out of range.");

            if (definition.ConveyorShelfIndices.Contains(shelfFilter.ShelfIndex))
                throw new InvalidOperationException($"{definition.name}: conveyor shelf {shelfFilter.ShelfIndex} cannot be filtered.");
        }

        int filteredColumnCount = definition.ShelfFilters.Sum(shelfFilter => board.Shelves[shelfFilter.ShelfIndex].Capacity);

        if (definition.FilteredEmptyColumnCount > filteredColumnCount)
            throw new InvalidOperationException($"{definition.name}: {definition.FilteredEmptyColumnCount} filtered empty columns exceed the {filteredColumnCount} columns of filtered shelves.");
    }

    private static void ValidateConveyorBoard(TimedLevelDefinition definition, BoardStateSnapshot board, int columnCount, int itemCount)
    {
        foreach (int shelfIndex in definition.ConveyorShelfIndices)
        {
            if (shelfIndex >= board.Shelves.Count)
                throw new InvalidOperationException($"{definition.name}: conveyor shelf index {shelfIndex} is out of range.");

            if (board.Shelves[shelfIndex].Capacity != TimedLevelLayoutRules.ConveyorShelfCapacity)
                throw new InvalidOperationException($"{definition.name}: conveyor shelf {shelfIndex} must have capacity {TimedLevelLayoutRules.ConveyorShelfCapacity}.");
        }

        int conveyorColumnCount = definition.ConveyorShelfIndices.Sum(shelfIndex => board.Shelves[shelfIndex].Capacity);
        int otherItemColumnCount = columnCount - conveyorColumnCount - definition.EmptyColumnCount;
        int capacity = conveyorColumnCount * TimedLevelLayoutRules.MaximumConveyorColumnDepth
            + Math.Max(0, otherItemColumnCount) * TimedLevelLayoutRules.MaximumColumnDepth;

        if (itemCount > capacity)
            throw new InvalidOperationException($"{definition.name}: {itemCount} items exceed the conveyor board capacity of {capacity}.");
    }

    private static void ValidateVariantLayout(TimedLevelDefinition definition, BoardStateSnapshot board, TimedLevelVariant variant, int variantIndex)
    {
        BoardStateSnapshot layout = variant.CreateLayout();

        if (layout.Shelves.Count != board.Shelves.Count)
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incompatible shelf count.");

        HashSet<int> closedShelfIndices = new HashSet<int>(definition.ClosedShelves.Select(closedShelf => closedShelf.ShelfIndex));
        HashSet<int> conveyorShelfIndices = new HashSet<int>(definition.ConveyorShelfIndices);

        for (int shelfIndex = 0; shelfIndex < layout.Shelves.Count; shelfIndex++)
        {
            ShelfStateSnapshot shelf = layout.Shelves[shelfIndex];

            if (shelf.Capacity != board.Shelves[shelfIndex].Capacity)
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incompatible shelf capacity.");

            bool shouldBeOpen = !closedShelfIndices.Contains(shelfIndex);

            if (shelf.IsOpen != shouldBeOpen)
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incorrect open state for shelf {shelfIndex}.");

            if (!shelf.IsOpen && !shelf.Columns.All(column => column.IsEmpty))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has items on closed shelf {shelfIndex}.");

            if (shelf.HasMatch())
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} starts with an automatic match.");

            if (shelf.Columns.Any(column => column.Count > TimedLevelLayoutRules.MaximumColumnDepth))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} exceeds the supported column depth.");

            if (shelf.Columns.Any(column => HasAdjacentDuplicate(shelf, column)))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} contains adjacent items of the same type in a column.");

            if (shelf.IsConveyor != conveyorShelfIndices.Contains(shelfIndex))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incorrect conveyor state for shelf {shelfIndex}.");

            if (shelf.IsConveyor)
                ValidateConveyorShelfLayout(definition, shelf, shelfIndex, variantIndex);
        }

        if (layout.EmptyColumnCount != definition.EmptyColumnCount)
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has {layout.EmptyColumnCount} empty columns instead of {definition.EmptyColumnCount}.");

        int matchSize = board.Shelves[0].Capacity;
        Dictionary<ItemType, int> expectedCounts = definition.ItemGroups.ToDictionary(
            group => group.Type,
            group => checked(group.GroupCount * matchSize));
        Dictionary<ItemType, int> actualCounts = layout.Shelves
            .SelectMany(shelf => shelf.Columns)
            .SelectMany(column => column.Items)
            .GroupBy(type => type)
            .ToDictionary(group => group.Key, group => group.Count());

        if (expectedCounts.Count != actualCounts.Count
            || expectedCounts.Any(pair => !actualCounts.TryGetValue(pair.Key, out int count) || count != pair.Value))
        {
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} item counts differ from the definition.");
        }

        ValidateShelfFilterVariant(definition, variant, layout, variantIndex);
    }

    private static void ValidateShelfFilterVariant(TimedLevelDefinition definition, TimedLevelVariant variant, BoardStateSnapshot layout, int variantIndex)
    {
        Dictionary<int, ItemType[]> expectedFilters = definition.ShelfFilters.ToDictionary(
            shelfFilter => shelfFilter.ShelfIndex,
            shelfFilter => shelfFilter.AcceptedTypes.OrderBy(type => type).ToArray());

        for (int shelfIndex = 0; shelfIndex < layout.Shelves.Count; shelfIndex++)
        {
            ItemType[] expectedTypes = expectedFilters.TryGetValue(shelfIndex, out ItemType[] types) ? types : Array.Empty<ItemType>();

            if (!layout.Shelves[shelfIndex].AcceptedTypes.SequenceEqual(expectedTypes))
                throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} has an incorrect filter for shelf {shelfIndex}.");
        }

        int filteredEmptyColumnCount = TimedLevelLayoutRules.CountFilteredEmptyColumns(layout);

        if (filteredEmptyColumnCount < definition.FilteredEmptyColumnCount)
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} starts with {filteredEmptyColumnCount} filtered empty columns instead of at least {definition.FilteredEmptyColumnCount}.");
    }

    private static void ValidateConveyorShelfLayout(TimedLevelDefinition definition, ShelfStateSnapshot shelf, int shelfIndex, int variantIndex)
    {
        if (shelf.Columns.Any(column => column.Count > TimedLevelLayoutRules.MaximumConveyorColumnDepth))
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} exceeds the conveyor column depth on shelf {shelfIndex}.");

        if (!TimedLevelLayoutRules.IsConveyorStartFilled(shelf))
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} must start with every column of conveyor shelf {shelfIndex} filled and one of them holding two or more items.");

        if (shelf.Columns.Any(column => column.Count >= 2 && column.Items[column.Count - 1] == column.Items[0]))
            throw new InvalidOperationException($"{definition.name}: variant {variantIndex + 1} places the same type at both ends of a column on conveyor shelf {shelfIndex}.");
    }

    private static bool HasAdjacentDuplicate(ShelfStateSnapshot shelf, ColumnStateSnapshot column)
    {
        for (int index = 1; index < column.Count; index++)
        {
            ItemType type = column.Items[index];

            if (type == column.Items[index - 1] && !(shelf.IsFiltered && shelf.Accepts(type)))
                return true;
        }

        return false;
    }
}
